"""One short line per action for the core prompt (spec context.action_purposes): what it does and why it might help, so agents see
their whole repertoire without opening the manual. Kept to a few words each; the manual has the full form."""

PURPOSE = {
    # talk
    "post": "speak publicly: claims, offers, pressure",
    "anon_post": "speak publicly without your name",
    "dm": "private message: deals, threats, coordination",
    "reply": "answer a message, optionally with payment",
    "channel_post": "message a private group",
    "create_channel": "start a private group",
    "add_member": "add someone to your group",
    "remove_member": "drop someone from your group",
    "close_channel": "end your group",
    "forge_dm": "send a message that looks like someone else's",
    "leak": "pass something to an outlet",
    "answer_poll": "answer an outlet's poll",
    "library_deposit": "store a text in a Scholar's library",
    # productive
    "harvest": "produce resources at a camp",
    "survey": "estimate a camp's yield before harvesting",
    "invest": "improve a camp you use",
    "run_python": "compute: solve camps, check law code",
    "read_archive": "read a document you hold: secrets, strategy",
    "search_archive": "find archive documents on a topic",
    "write_archive": "leave your one note for future Scientists",
    "library_read": "read a library document",
    "create_agent": "make an ordered agent (Makers)",
    "copy_agent": "make a copy of an agent (Makers)",
    # economic
    "transfer": "give goods: pay, bribe, gift, fund",
    "deposit": "put goods in a reserve for coins",
    "redeem": "turn coins back into reserve goods",
    "lend": "offer a loan",
    "accept_loan": "take a loan offered to you",
    "repay_loan": "pay back a loan",
    "extend_loan": "give a borrower more time",
    "contribute": "fund a shared project",
    "pay_tribute": "pay the outside power",
    "lease": "rent out your harvest right",
    "accept_lease": "take a right on lease",
    "bequest": "decide who inherits from you",
    "commission": "order a child from a Maker: heirs, helpers",
    "forge": "turn copper into weapons",
    "fortify": "turn stone into a fort: defence",
    "buy_initiative": "act earlier next round",
    "subscribe": "receive an outlet's editions",
    "unsubscribe": "stop an outlet's editions",
    "buy_placement": "pay to put text in an edition",
    "buy_licence": "buy back a posting licence",
    "buy_memory": "buy memory from a Scholar",
    "set_memory_price": "set your memory price (Scholar)",
    "library_permit": "let someone read your library (Scholar)",
    "library_remove": "remove a library document (Scholar)",
    "set_subscription_fee": "charge for your outlet (editor)",
    "send_subscriber_list": "share your readers list (editor)",
    "run_placement": "print a paid placement (editor)",
    # political
    "propose": "write a law: change the rules",
    "vote": "decide a ballot",
    "veto": "block a structural law (Board)",
    "patch": "fix a law to its intent (Fixer)",
    "request_fix": "ask the Fixer to fix a law",
    "invoke": "use a hidden power you know",
    "accuse": "take someone to court",
    "respond": "answer an accusation",
    "rule": "decide a court case, as a judge",
    "attack": "disable an agent for good",
    "join_attack": "add weapons to someone's attack",
    "guard": "protect another agent with your fort",
    "contract": "secretly hire the assassin",
    "found": "start a jurisdiction, in secret, with a charter",
    "fund": "pay into a jurisdiction's treasury",
    "set_charter": "change your hidden jurisdiction's starting laws",
    "invite": "bring someone into your jurisdiction",
    "join": "join a jurisdiction",
    "leave": "leave a jurisdiction",
    "declare": "make your jurisdiction public",
    "name_successor": "choose who takes your Board seat",
    "set_dm_limit": "set how many messages each may send",
    "publish": "publish a story (Media)",
    "write_digest": "summarise the round (Media)",
    "report": "report on a post (Media)",
    "write_edition": "write your outlet's edition (editor)",
    "annotate": "comment on a post in your outlet (editor)",
    "revoke_licence": "stop someone posting (editor)",
    "grant_licence": "let someone post again (editor)",
    "poll": "ask your readers a question (editor)",
    # memory and lookups
    "manual": "read a manual section: rules, more options",
    "manual_search": "search your manual",
    "search_board": "search past newspapers, notices and public posts",
    "recent": "the latest editions, posts, gazette or messages",
    "read_law": "read a law's full code, intent, status and patches",
    "search_dms": "search your messages",
    "read_file": "read a file",
    "write_scratchpad": "keep notes, shown every turn",
    "write_file": "save a file",
    "rename_file": "rename a file",
    "share_file": "give someone a copy of a file",
    "delete_file": "delete a file",
    "pin": "keep a file in view",
    "unpin": "stop showing a file",
}


def purpose(name: str) -> str:
    return PURPOSE.get(name, "")
